### ISSUE TITLE
Normalize that does not hit the disk no matter the OS

### ISSUE THREAD

**Issue by Ciantic** [dylni/normpath#2]
I don't know why your implementation of normalize hits the disk by default, but there should be option at least to normalize without hitting disk. That is the default behavior in other languages.

Reason it's important to have a normalize call that doesn't hit the disk in any OS is to guarantee that it doesn't cause IO. Right now there is not a single function to normalize path without hitting IO in some OS.

Examples from node and python:

(Notice that I don't have directory called `foo` thus it can't hit the disk)

## Python

Windows:

```python3
import os.path
os.path.normpath("/foo/../zoo")
'\\zoo'
```

Linux: 

```
import os.path
 os.path.normpath("/foo/../zoo")
'/zoo'
```

## Node

Windows: 
```bash
C:\Users\jarip>node
Welcome to Node.js v12.18.0.
> path.normalize("/foo/../zoo")
'\\zoo'
```

Linux:
```
Welcome to Node.js v16.1.0.
Type ".help" for more information.
> path.normalize("/foo/../zoo")
'/zoo'
```

----

Simple solution would be to implement the `normalize_virtually` on Linux too. Then there would be a single function that is guaranteed to not hit the disk no matter the OS.

**Comment by dylni** [comment]
This is a great question!

> Simple solution would be to implement the `normalize_virtually` on Linux too.

Unfortunately, there's no way to implement this function correctly on Linux. In your example, if `/foo` is a symlink to `/bar/baz`, normalizing `/foo/../zoo` to `/zoo` would be incorrect. The correct normalized path would be `/bar/zoo`, which can't be determined without IO.

> Reason it's important to have a normalize call that doesn't hit the disk in any OS is to guarantee that it doesn't cause IO. Right now there is not a single function to normalize path without hitting IO in some OS.

Do you have a use case for this even if the function can return a wrong path? I've avoided implementing this function to avoid the unsafe default behavior of other languages.

**Comment by dylni** [comment]
> It just hits the disk twice. First with normalize, and then with the read or stat or what ever you do with the file path.

If you mean that a user could use this path later, that's true but not controlled by this crate. `PathExt::normalize` shouldn't be making multiple IO calls. If you're only using a file path for other things, `PathExt::normalize` isn't necessary. It's commonly used to create a path that looks better to display for users.

Also, there's no single syscall I've seen on Unix to both open a file and normalize it, so that might be difficult to achieve.

> Also I was doing this in parallel with all the inputs and I was not expecting this part of the code to hit disk

This is good to know. I'll make this clearer in the documentation.

> Isn't that part usually normalized with realpath?

Yes, but if you normalize it incorrectly before calling realpath, you'll be using the wrong path. That can cause dangerous security issues depending on how you use it.

> Windows has also symlinks, and I don't expect normalization to remove symlinks I guess, if it doesn't hit the disk.

This is understandable, and languages choosing an unsafe default makes this confusing. Windows and Unix paths are different, even though many normalization implementations treat them the same. Using the previous example, if `foo` is a symlink to `bar/baz` the normalized version of `foo/../zoo` is:
- `zoo` on Windows
- `bar/zoo` on Unix

This is why symlinks need to be resolved on Unix when normalizing the path. `..` directories can't be resolved without resolving symlinks.

**Comment by dylni** [comment]
I'm closing this issue, since no new comments have been added for 3 weeks. Please reopen it if you have any additional comments.
