### ISSUE TITLE
Please  add methods to convert `VerbatimDisk` <--> `Disk` , or `starts_with_ignore_verbatim` method

### ISSUE THREAD

**Issue by viruscamp** [dylni/normpath#21]
Would you please add methods to convert between:  
`VerbatimUNC` <--> `UNC`  
`VerbatimDisk` <--> `Disk`  

Or add another `starts_with_ignore_verbatim` method.

**Comment by dylni** [comment]
There is actually another crate designed for this purpose: [dunce](https://crates.io/crates/dunce). However, it necessarily will not be able to handle all paths, since Windows has some `VerbatimUNC` and `VerbatimDisk` paths that cannot be represented as `UNC` and `Disk` paths.

`normpath` is meant to ease working with any path in its original format. It does not attempt to convert between different paths, since not all paths would be representable.

Let me know if this solves your use case or you have other concerns that may be helped by this crate! :slightly_smiling_face:
